### ISSUE TITLE
consider renaming

### ISSUE THREAD

**Issue by sarahcd** [movestore/Filter-Day-or-Night#3]
This and other filter apps can/could be used to annotate categories to the full dataset (rather than filter/remove data). This makes them more generally useful. We have gotten some requests that indicate people don't realize this annotation feature is available using this app. Is there a better app name to explain these two tasks?

**Comment by andreakoelzsch** [comment]
We could call all the Apps Filter/Annotate ... I would rather update all of them together with switch to sf in June. Can we make a list, which ones should that be?
